eureka:
  client:
    serviceUrl:
      #defaultZone: http://BPIEureka-1635971335.eu-central-1.elb.amazonaws.com/eureka
      defaultZone: http://localhost:8762/eureka
  instance:
    statusPageUrlPath: /my_info
    healthCheckUrlPath: /my_health
    virtualHostName: ConfigServer
    metadataMap:
      appOwner: Vanadis
      descripction: Servidor de configuración